services:
  main-server:
    build: ./
    image: main-server
    container_name: main-server
    ports:
      - "${TOMCAT_PORT}:${TOMCAT_PORT}"
    depends_on:
      - main-db
    restart: on-failure
    environment:
      - DB_URL=jdbc:postgresql://main-db:${DB_PORT}/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TOMCAT_PORT=${TOMCAT_PORT}

  main-db:
    image: postgres:alpine
    container_name: main-db
    command: -p ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}