spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/db-changelog-master.yaml
    default-schema: public
    contexts: migrated

logging-server:
  url: http://localhost:9099
