spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/request_logs
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/db-changelog-master.yaml
    default-schema: public
    contexts: migrated
